# Generated by Django 2.0.1 on 2018-10-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pm25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='城市名')),
                ('pm25_value', models.IntegerField(default=0, verbose_name='PM25值')),
                ('adive', models.TextField(verbose_name='建议')),
                ('step', models.TextField(verbose_name='措施')),
            ],
        ),
    ]
