# Generated by Django 2.0.1 on 2018-10-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm25', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm25',
            name='grade',
            field=models.TextField(blank=True, null=True, verbose_name='等级'),
        ),
    ]
